/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 computer.gltf --transform
Author: Mikkel Garde Blaase (https://sketchfab.com/plorigon)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/killer-beats-casette-mixstation-1cc1eda430c74e3ea8f39284b2fb01d8
Title: "Killer Beats" Casette Mixstation
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/computer-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-6.5, -0.03, 1.77]} rotation={[Math.PI, 1.28, Math.PI / 2]} scale={[1.05, 0.96, 1]}>
        <mesh geometry={nodes.casette_base_low002_M_Details_Translucent_0.geometry} material={materials.M_Details_Translucent} />
        <mesh geometry={nodes.casette_base_low002_M_Details_0.geometry} material={materials.M_Details} />
      </group>
      <group position={[-6.54, 0.76, 1.63]} rotation={[Math.PI, 1.28, Math.PI / 2]} scale={[1.05, 0.96, 1]}>
        <mesh geometry={nodes.casette_base_low003_M_Details_Translucent_0.geometry} material={materials.M_Details_Translucent} />
        <mesh geometry={nodes.casette_base_low003_M_Details_0.geometry} material={materials.M_Details} />
      </group>
      <group position={[5.42, -0.03, -8.57]} rotation={[0, -0.65, -Math.PI / 2]} scale={[1.05, 0.96, 1]}>
        <mesh geometry={nodes.casette_base_low004_M_Details_Translucent_0.geometry} material={materials.M_Details_Translucent} />
        <mesh geometry={nodes.casette_base_low004_M_Details_0.geometry} material={materials.M_Details} />
      </group>
      <group position={[5.38, 0.83, -8.55]} rotation={[0, -0.17, -Math.PI / 2]} scale={[1.05, 0.96, 1]}>
        <mesh geometry={nodes.casette_base_low009_M_Details_Translucent_0.geometry} material={materials.M_Details_Translucent} />
        <mesh geometry={nodes.casette_base_low009_M_Details_0.geometry} material={materials.M_Details} />
      </group>
      <group position={[5.83, 0.1, 1.82]} rotation={[0, 1.5, -Math.PI / 2]} scale={[1.05, 0.96, 1]}>
        <mesh geometry={nodes.casette_base_low010_M_Details_Translucent_0.geometry} material={materials.M_Details_Translucent} />
        <mesh geometry={nodes.casette_base_low010_M_Details_0.geometry} material={materials.M_Details} />
      </group>
      <group position={[5.83, 0.93, 1.82]} rotation={[-Math.PI, -0.81, -Math.PI / 2]} scale={[1.05, 0.96, 1]}>
        <mesh geometry={nodes.casette_base_low011_M_Details_Translucent_0.geometry} material={materials.M_Details_Translucent} />
        <mesh geometry={nodes.casette_base_low011_M_Details_0.geometry} material={materials.M_Details} />
      </group>
      <group position={[13.58, 0.01, 8.04]} rotation={[0.04, 0.62, 1.55]}>
        <mesh geometry={nodes.casette_base_low012_M_Details_Translucent_0.geometry} material={materials.M_Details_Translucent} />
        <mesh geometry={nodes.casette_base_low012_M_Details_0.geometry} material={materials.M_Details} />
      </group>
      <mesh geometry={nodes.kb_base_low001_M_Keyboard_0.geometry} material={materials.M_Keyboard} position={[0.04, 0.76, 6.78]} rotation={[-Math.PI, 0.13, 0]} />
      <mesh geometry={nodes.SM_Keyboard_Lid_M_Keyboard_Translucent_0.geometry} material={materials.M_Keyboard_Translucent} position={[8.4, 2.04, 8.47]} rotation={[3.12, 0.13, 0]} />
      <mesh geometry={nodes.SM_Monitor_M_Monitor_0.geometry} material={materials.M_Monitor} position={[-0.8, 6.6, -3.29]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.strip_low_M_Details_0.geometry} material={materials.M_Details} position={[4.16, 0.96, -12.62]} rotation={[-2.81, 0.34, 1.02]} />
      <mesh geometry={nodes.SM_Cables_M_Details_0.geometry} material={materials.M_Details} position={[12.35, 6.02, -3.06]} rotation={[Math.PI / 2, 0, 0.24]} />
      <mesh geometry={nodes.ductTape_low_M_Details_0.geometry} material={materials.M_Details} position={[0.17, 0.21, -15.17]} rotation={[3.09, -0.03, -0.01]} />
      <mesh geometry={nodes.tape_base_low001_M_Details_0.geometry} material={materials.M_Details} position={[-4.46, 12.14, -3.27]} rotation={[0.03, -0.93, 0.03]} />
      <mesh geometry={nodes.SM_Speakers_M_Speakers_0.geometry} material={materials.M_Speakers} position={[11.81, 2.21, -0.19]} rotation={[Math.PI / 2, 0, 0.36]} scale={1.27} />
      <mesh geometry={nodes.ductTape_low001_M_Details_0.geometry} material={materials.M_Details} position={[11.73, 4.47, -3.96]} rotation={[-2.75, -0.01, 3.09]} scale={[-0.61, 0.61, 0.61]} />
      <mesh geometry={nodes.ductTape_low002_M_Details_0.geometry} material={materials.M_Details} position={[12.61, 1.26, -4.74]} rotation={[-2.14, -0.13, 3.07]} scale={[-0.61, 0.61, 0.61]} />
      <mesh geometry={nodes.strip_low001_M_Details_0.geometry} material={materials.M_Details} position={[17.86, -0.26, -3.35]} rotation={[2.99, -0.54, 0.19]} />
      <mesh geometry={nodes.strip_low002_M_Details_0.geometry} material={materials.M_Details} position={[16.83, -0.26, -0.24]} rotation={[0.43, -1.27, -2.46]} />
      <mesh geometry={nodes.tape_base_low003_M_Details_0.geometry} material={materials.M_Details} position={[-10.93, 0, 5.67]} rotation={[-0.06, -0.46, 1.55]} />
      <mesh geometry={nodes.tape_base_low004_M_Details_0.geometry} material={materials.M_Details} position={[8.18, 1.43, 10.29]} rotation={[-Math.PI, -1.43, -1.85]} />
      <mesh geometry={nodes.tape_base_low005_M_Details_0.geometry} material={materials.M_Details} position={[-10.2, 0.17, 4.24]} rotation={[3.02, -0.05, 1.6]} />
      <mesh geometry={nodes.casette_base_low005_M_Details_Translucent_0.geometry} material={materials.M_Details_Translucent} position={[-0.42, 12.29, -3.23]} rotation={[-3.14, 0.12, -1.57]} />
      <mesh geometry={nodes.casette_lid_low002_M_Details_0.geometry} material={materials.M_Details} position={[-0.27, 11.93, -4.48]} rotation={[-3.14, 0.12, -1.57]} />
      <mesh geometry={nodes.casette_base_low006_M_Details_Translucent_0.geometry} material={materials.M_Details_Translucent} position={[14.5, 0.88, 1.79]} rotation={[1.48, 0.17, 0.47]} />
      <mesh geometry={nodes.casette_lid_low003_M_Details_0.geometry} material={materials.M_Details} position={[14.39, -0.43, 1.73]} rotation={[1.48, 0.17, 0.47]} />
      <mesh geometry={nodes.casette_base_low007_M_Details_Translucent_0.geometry} material={materials.M_Details_Translucent} position={[-1.05, 13.01, -3.66]} rotation={[-3.14, -0.2, -1.57]} />
      <mesh geometry={nodes.casette_lid_low004_M_Details_0.geometry} material={materials.M_Details} position={[-1.3, 12.65, -4.9]} rotation={[-3.14, -0.2, -1.57]} />
      <mesh geometry={nodes.tape_base_low006_M_Details_0.geometry} material={materials.M_Details} position={[-9.28, 0.88, -1.2]} rotation={[1.57, -0.22, -0.06]} />
      <mesh geometry={nodes.tape_base_low007_M_Details_0.geometry} material={materials.M_Details} position={[11.71, 9.95, -0.4]} rotation={[-0.02, -0.82, 3.13]} />
      <mesh geometry={nodes.tape_base_low008_M_Details_0.geometry} material={materials.M_Details} position={[-7.23, 0.1, -8.26]} rotation={[-3.13, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.tape_base_low009_M_Details_0.geometry} material={materials.M_Details} position={[-7.23, 0.57, -8.32]} rotation={[-0.02, -0.08, 1.57]} />
      <mesh geometry={nodes.tape_base_low010_M_Details_0.geometry} material={materials.M_Details} position={[-7.86, -0.39, -7.88]} rotation={[1.56, -0.06, -1.41]} />
      <mesh geometry={nodes.tape_base_low011_M_Details_0.geometry} material={materials.M_Details} position={[-7.23, 0.96, -8.33]} rotation={[3.12, -0.26, -1.56]} />
      <mesh geometry={nodes.tape_base_low012_M_Details_0.geometry} material={materials.M_Details} position={[14.5, 0.88, 1.79]} rotation={[1.48, 0.17, 0.47]} />
      <mesh geometry={nodes.tape_base_low013_M_Details_0.geometry} material={materials.M_Details} position={[-1.05, 13.01, -3.66]} rotation={[-3.14, -0.2, -1.57]} />
      <mesh geometry={nodes.tape_base_low014_M_Details_0.geometry} material={materials.M_Details} position={[-0.42, 12.29, -3.23]} rotation={[-3.14, 0.12, 1.57]} />
      <mesh geometry={nodes.Plane_M_Floor_0.geometry} material={materials.M_Floor} position={[0.18, -0.52, 0.54]} rotation={[0, -0.47, 0]} scale={28.14} />
    </group>
  )
}

useGLTF.preload('/computer-transformed.glb')
